<a href="https://colab.research.google.com/github/pipeberrio/Analitica/blob/main/ENTREGA3_Proyecto_Integrador_Analitica_de_Negocios.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**ENTREGA NÚMERO 3 PROYECTO INTEGRADOR ANALÍTICA DE NEGOCIOS I**


**Título:** Análisis de la Demanda de Vehículos y Pasajeros del Transporte Urbano en Grandes Ciudades y Áreas Metropolitanas de Colombia (2019-2024)


**Integrantes:** Jaime Luis Villadiego Meza, Daniela Jiménez Gómez, Raúl Felipe Berrío Gómez, Daniel Eduardo Heredia Bustamante

In [1]:
#Con este código se lee la información de la base de datos 1 (Transporte urbano de pasajeros 2019 a 2024) en la hoja que se requiere

import pandas as pd
import numpy as np

file_id = '1OoF_Exhf6rioIRna1SrAZ8h_qUwswInJ'
hoja = 'Anexo 1'
df = pd.read_excel(f'https://docs.google.com/uc?export=download&id={file_id}', sheet_name = hoja, header=6, usecols = "A:G,J:O,R:W").loc[:23] #se dejan las 3 variables de interés y eliminan las columnas separadoras
df

,Áreas Metropolitanas y Ciudades,Promedio mensual de vehículos afiliados,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Promedio mensual de vehículos en servicio,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Total pasajeros transportados (miles),Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22
0,NaN,2019.000000,2020.000000,2021,2022,2023,2024p,2019.000000,2020.000000,2021,2022,2023,2024p,2019.000,2020.000,2021,2022,2023,2024p
1,Total general,39012.666667,38312.333333,37726.333333,35885.333333,35839,35182,33998.666667,22227.666667,27937.666667,28241,28691.666667,28468,938881.682,245189.798,454952.784,731234.348,744184.558,771537.752
2,Área Metropolitana de Barranquilla1,3397.000000,3422.333333,3412,3346.333333,3364,3283,3086.333333,1686.333333,2638,2624,2655.333333,2534.666667,68281.480,23213.447,38962.117,51919.151,49653.966,44527.547
3,Área Metropolitana de Bogotá2,15272.333333,14665.000000,14419.666667,12912.666667,13330.333333,12858.666667,13907.000000,11202.333333,12294,11538,11869.333333,11673.666667,451580.212,117013.342,207075.493,360461.029,368084.604,395139.042
4,Área Metropolitana de Bucaramanga3,1304.333333,1261.666667,1243.666667,1216.666667,1211.333333,1185.333333,1242.333333,772.666667,1002.666667,977.333333,925,930,19741.500,4114.659,7122.776,12728.739,13053.388,15082.321
5,Área Metropolitana de Cali4,1982.333333,1992.000000,1958.666667,1964.333333,1797.666667,1801.666667,1397.000000,885.333333,645.333333,1037.666667,1008.333333,1133.666667,46794.710,11023.112,9814.149,26092.802,25553.069,28862.331
6,Área Metropolitana de Cúcuta5,1767.000000,1739.333333,1673.333333,1653,1671.333333,1648,1432.333333,733.666667,1012.666667,1085,1080.666667,1104.666667,18900.476,6790.799,12497.048,16092.447,16759.731,16312.188
7,Área Metropolitana de Manizales6,1030.000000,1037.000000,992.333333,1005,1015.666667,1016,899.666667,444.000000,831.666667,829,847.333333,854,15805.481,2683.918,7734.109,11793.062,12193.316,12645.157
8,Área Metropolitana del Valle de Aburrá (Medell...,5819.000000,5918.000000,5925.333333,5937.333333,5923.666667,5899.333333,5276.333333,4047.666667,4923.333333,5074.666667,5167,5183.333333,175397.817,51178.162,102748.447,159206.095,164274.964,162934.413
9,Área Metropolitana Centro de Occidente (Pereira)8,833.666667,839.333333,826,910,902,907,683.666667,325.000000,529.666667,623.333333,636.333333,649,18234.884,4895.814,9620.801,15721.84,15457.585,16146.857
10,Armenia,341.666667,344.000000,343,344,345.666667,344,284.333333,170.000000,244.666667,245.666667,250.333333,249.666667,5322.660,1276.224,3185.506,4079.014,3848.787,4171.55
11,Cartagena,1151.000000,1036.000000,1012,869.333333,853,849.666667,984.000000,428.666667,580,607.333333,555.666667,543.333333,25602.039,5085.441,10006.101,14023.711,14922.436,14437.659
12,Florencia,73.000000,75.333333,75,76,84,75,58.333333,20.666667,46.666667,39.333333,37.333333,36.333333,890.761,224.490,374.7,507.397,489.107,459.7
13,Ibagué,1010.000000,973.000000,964,919,906,905.333333,840.000000,248.666667,601,626.333333,612.666667,628.666667,18612.480,2601.209,9108.697,11248.4,11669.637,11626.824
14,Montería,259.000000,259.000000,259,252.333333,239,241,200.000000,60.666667,102.666667,137.666667,137.666667,122,3732.668,834.919,1021.74,933.329,1002.022,1237.73
15,Neiva,660.333333,654.333333,647,645,633,632,441.333333,152.333333,250.666667,264,271.666667,267.666667,6208.198,865.041,2393.575,3401.325,3290.054,3430.686
16,Pasto,502.000000,502.000000,502,502,486,488,478.333333,196.333333,338.666667,378,402.333333,393.666667,7992.793,977.363,3084.808,5204.716,5422.828,5808.573
17,Popayán,634.000000,626.000000,616,498,466,466,467.000000,116.666667,265.666667,296,321,313.333333,6933.853,1594.323,3756.322,4077.458,4963.82,4598.268
18,Quibdó,194.000000,194.000000,174.666667,160.333333,163.666667,166.333333,123.666667,100.333333,99,86,86.666667,89.666667,2778.143,1073.863,2088.197,1492.432,1414.046,1428.312
19,Santa Marta,679.000000,673.000000,666.666667,658,633.666667,608,649.000000,201.000000,451,576.666667,581,570.333333,25948.771,7123.892,15723.474,21218.291,20230.427,20775.493
20,Sincelejo**,85.000000,85.000000,**,**,**,**,75.000000,75.000000,**,**,**,**,822.627,492.551,**,**,**,**
21,Tunja,532.000000,532.000000,532,532,532,532,426.666667,129.000000,284.333333,359.666667,343,345,4330.678,446.366,1629.569,2371.665,2630.385,3269.446
22,Valledupar,484.000000,482.000000,482,482,284,284,130.666667,31.333333,58.333333,56.333333,117,94.666667,1573.613,47.228,187.35,276.004,1140.604,927.704
23,Villavicencio,1002.000000,1002.000000,1002,1002,997,991.666667,915.666667,200.000000,737.666667,779,786,750.666667,13395.838,1633.635,6817.805,8385.441,8129.782,7715.951

In [2]:
#CON LA SIGUIENTE INSTRUCCIÓN DEJAMOS LOS NOMBRES DE LAS COLUMNAS CON LAS VARIABLES DESEADAS
columns_names = ['Áreas Metropolitanas y Ciudades', 'Promedio mensual de vehículos afiliados 2019', '2020','2021','2022 ','2023','2024', 'Promedio mensual de vehículos en servicio 2019', '2020','2021','2022','2023','2024', 'Total pasajeros transportados (miles) 2019', '2020','2021','2022','2023','2024 ']
df.columns = columns_names
df = df.drop(index=0)
df = df.drop(index=1)
df = df.reset_index(drop=True)
df

,Áreas Metropolitanas y Ciudades,Promedio mensual de vehículos afiliados 2019,2020,2021,2022,2023,2024,Promedio mensual de vehículos en servicio 2019,2020,2021,2022,2023,2024,Total pasajeros transportados (miles) 2019,2020,2021,2022,2023,2024
0,Área Metropolitana de Barranquilla1,3397.000000,3422.333333,3412,3346.333333,3364,3283,3086.333333,1686.333333,2638,2624,2655.333333,2534.666667,68281.480,23213.447,38962.117,51919.151,49653.966,44527.547
1,Área Metropolitana de Bogotá2,15272.333333,14665.000000,14419.666667,12912.666667,13330.333333,12858.666667,13907.000000,11202.333333,12294,11538,11869.333333,11673.666667,451580.212,117013.342,207075.493,360461.029,368084.604,395139.042
2,Área Metropolitana de Bucaramanga3,1304.333333,1261.666667,1243.666667,1216.666667,1211.333333,1185.333333,1242.333333,772.666667,1002.666667,977.333333,925,930,19741.500,4114.659,7122.776,12728.739,13053.388,15082.321
3,Área Metropolitana de Cali4,1982.333333,1992.000000,1958.666667,1964.333333,1797.666667,1801.666667,1397.000000,885.333333,645.333333,1037.666667,1008.333333,1133.666667,46794.710,11023.112,9814.149,26092.802,25553.069,28862.331
4,Área Metropolitana de Cúcuta5,1767.000000,1739.333333,1673.333333,1653,1671.333333,1648,1432.333333,733.666667,1012.666667,1085,1080.666667,1104.666667,18900.476,6790.799,12497.048,16092.447,16759.731,16312.188
5,Área Metropolitana de Manizales6,1030.000000,1037.000000,992.333333,1005,1015.666667,1016,899.666667,444.000000,831.666667,829,847.333333,854,15805.481,2683.918,7734.109,11793.062,12193.316,12645.157
6,Área Metropolitana del Valle de Aburrá (Medell...,5819.000000,5918.000000,5925.333333,5937.333333,5923.666667,5899.333333,5276.333333,4047.666667,4923.333333,5074.666667,5167,5183.333333,175397.817,51178.162,102748.447,159206.095,164274.964,162934.413
7,Área Metropolitana Centro de Occidente (Pereira)8,833.666667,839.333333,826,910,902,907,683.666667,325.000000,529.666667,623.333333,636.333333,649,18234.884,4895.814,9620.801,15721.84,15457.585,16146.857
8,Armenia,341.666667,344.000000,343,344,345.666667,344,284.333333,170.000000,244.666667,245.666667,250.333333,249.666667,5322.660,1276.224,3185.506,4079.014,3848.787,4171.55
9,Cartagena,1151.000000,1036.000000,1012,869.333333,853,849.666667,984.000000,428.666667,580,607.333333,555.666667,543.333333,25602.039,5085.441,10006.101,14023.711,14922.436,14437.659
10,Florencia,73.000000,75.333333,75,76,84,75,58.333333,20.666667,46.666667,39.333333,37.333333,36.333333,890.761,224.490,374.7,507.397,489.107,459.7
11,Ibagué,1010.000000,973.000000,964,919,906,905.333333,840.000000,248.666667,601,626.333333,612.666667,628.666667,18612.480,2601.209,9108.697,11248.4,11669.637,11626.824
12,Montería,259.000000,259.000000,259,252.333333,239,241,200.000000,60.666667,102.666667,137.666667,137.666667,122,3732.668,834.919,1021.74,933.329,1002.022,1237.73
13,Neiva,660.333333,654.333333,647,645,633,632,441.333333,152.333333,250.666667,264,271.666667,267.666667,6208.198,865.041,2393.575,3401.325,3290.054,3430.686
14,Pasto,502.000000,502.000000,502,502,486,488,478.333333,196.333333,338.666667,378,402.333333,393.666667,7992.793,977.363,3084.808,5204.716,5422.828,5808.573
15,Popayán,634.000000,626.000000,616,498,466,466,467.000000,116.666667,265.666667,296,321,313.333333,6933.853,1594.323,3756.322,4077.458,4963.82,4598.268
16,Quibdó,194.000000,194.000000,174.666667,160.333333,163.666667,166.333333,123.666667,100.333333,99,86,86.666667,89.666667,2778.143,1073.863,2088.197,1492.432,1414.046,1428.312
17,Santa Marta,679.000000,673.000000,666.666667,658,633.666667,608,649.000000,201.000000,451,576.666667,581,570.333333,25948.771,7123.892,15723.474,21218.291,20230.427,20775.493
18,Sincelejo**,85.000000,85.000000,**,**,**,**,75.000000,75.000000,**,**,**,**,822.627,492.551,**,**,**,**
19,Tunja,532.000000,532.000000,532,532,532,532,426.666667,129.000000,284.333333,359.666667,343,345,4330.678,446.366,1629.569,2371.665,2630.385,3269.446
20,Valledupar,484.000000,482.000000,482,482,284,284,130.666667,31.333333,58.333333,56.333333,117,94.666667,1573.613,47.228,187.35,276.004,1140.604,927.704
21,Villavicencio,1002.000000,1002.000000,1002,1002,997,991.666667,915.666667,200.000000,737.666667,779,786,750.666667,13395.838,1633.635,6817.805,8385.441,8129.782,7715.951

In [3]:
#CONVERTIMOS EL INTERIOR DEL DATAFRAME EN ENTEROS
import pandas as pd

df['Promedio mensual de vehículos afiliados 2019'] = df['Promedio mensual de vehículos afiliados 2019'].astype(int)  #funciona bien
df['2020'] = df['2020'].astype(int) # funciona bien


fila_a_eliminar = 18 # Fila a eliminar temporalmente
fila_eliminada = df.iloc[fila_a_eliminar:fila_a_eliminar+1] # Guardar la fila a eliminar en un DataFrame temporal
df = df.drop(fila_a_eliminar) # Eliminar la fila del DataFrame original
df['2021'] = df['2021'].astype(int) # Realizar operaciones en el DataFrame modificado
df = pd.concat([df.iloc[:fila_a_eliminar], fila_eliminada, df.iloc[fila_a_eliminar:]], ignore_index=True) # Reinsertar la fila eliminada

fila_a_eliminar = 18 # Fila a eliminar temporalmente
fila_eliminada = df.iloc[fila_a_eliminar:fila_a_eliminar+1] # Guardar la fila a eliminar en un DataFrame temporal
df = df.drop(fila_a_eliminar) # Eliminar la fila del DataFrame original
df['2022'] = df['2022'].astype(int) # Realizar operaciones en el DataFrame modificado
df = pd.concat([df.iloc[:fila_a_eliminar], fila_eliminada, df.iloc[fila_a_eliminar:]], ignore_index=True) # Reinsertar la fila eliminada

fila_a_eliminar = 18 # Fila a eliminar temporalmente
fila_eliminada = df.iloc[fila_a_eliminar:fila_a_eliminar+1] # Guardar la fila a eliminar en un DataFrame temporal
df = df.drop(fila_a_eliminar) # Eliminar la fila del DataFrame original
df['2023'] = df['2023'].astype(int) # Realizar operaciones en el DataFrame modificado
df = pd.concat([df.iloc[:fila_a_eliminar], fila_eliminada, df.iloc[fila_a_eliminar:]], ignore_index=True) # Reinsertar la fila eliminada

fila_a_eliminar = 18 # Fila a eliminar temporalmente
fila_eliminada = df.iloc[fila_a_eliminar:fila_a_eliminar+1] # Guardar la fila a eliminar en un DataFrame temporal
df = df.drop(fila_a_eliminar) # Eliminar la fila del DataFrame original
df['2024'] = df['2024'].astype(int) # Realizar operaciones en el DataFrame modificado
df = pd.concat([df.iloc[:fila_a_eliminar], fila_eliminada, df.iloc[fila_a_eliminar:]], ignore_index=True) # Reinsertar la fila eliminada

df['Promedio mensual de vehículos en servicio 2019'] = df['Promedio mensual de vehículos en servicio 2019'].astype(int)  #funciona bien
df['Total pasajeros transportados (miles) 2019'] = df['Total pasajeros transportados (miles) 2019'].astype(int)  #funciona bien
df = df.replace('**', np.nan)#En nuestra base de datos los datos faltantes aparecían con los caracteres ** en la ciudad de Sincelejo y, por tanto reemplazó por nan
df

<ipython-input-3-0f79d1e094a1>:34: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace('**', np.nan)#En nuestra base de datos los datos faltantes aparecían con los caracteres ** en la ciudad de Sincelejo y, por tanto reemplazó por nan

,Áreas Metropolitanas y Ciudades,Promedio mensual de vehículos afiliados 2019,2020,2021,2022,2023,2024,Promedio mensual de vehículos en servicio 2019,2020,2021,2022,2023,2024,Total pasajeros transportados (miles) 2019,2020,2021,2022,2023,2024
0,Área Metropolitana de Barranquilla1,3397,3422,3412.0,3346.333333,3364.0,3283.0,3086,1686,2638.0,2624.0,2655.0,2534.0,68281,23213,38962.0,51919.0,49653.0,44527.547
1,Área Metropolitana de Bogotá2,15272,14665,14419.0,12912.666667,13330.0,12858.0,13907,11202,12294.0,11538.0,11869.0,11673.0,451580,117013,207075.0,360461.0,368084.0,395139.042
2,Área Metropolitana de Bucaramanga3,1304,1261,1243.0,1216.666667,1211.0,1185.0,1242,772,1002.0,977.0,925.0,930.0,19741,4114,7122.0,12728.0,13053.0,15082.321
3,Área Metropolitana de Cali4,1982,1992,1958.0,1964.333333,1797.0,1801.0,1397,885,645.0,1037.0,1008.0,1133.0,46794,11023,9814.0,26092.0,25553.0,28862.331
4,Área Metropolitana de Cúcuta5,1767,1739,1673.0,1653.000000,1671.0,1648.0,1432,733,1012.0,1085.0,1080.0,1104.0,18900,6790,12497.0,16092.0,16759.0,16312.188
5,Área Metropolitana de Manizales6,1030,1037,992.0,1005.000000,1015.0,1016.0,899,444,831.0,829.0,847.0,854.0,15805,2683,7734.0,11793.0,12193.0,12645.157
6,Área Metropolitana del Valle de Aburrá (Medell...,5819,5918,5925.0,5937.333333,5923.0,5899.0,5276,4047,4923.0,5074.0,5167.0,5183.0,175397,51178,102748.0,159206.0,164274.0,162934.413
7,Área Metropolitana Centro de Occidente (Pereira)8,833,839,826.0,910.000000,902.0,907.0,683,325,529.0,623.0,636.0,649.0,18234,4895,9620.0,15721.0,15457.0,16146.857
8,Armenia,341,344,343.0,344.000000,345.0,344.0,284,170,244.0,245.0,250.0,249.0,5322,1276,3185.0,4079.0,3848.0,4171.550
9,Cartagena,1151,1036,1012.0,869.333333,853.0,849.0,984,428,580.0,607.0,555.0,543.0,25602,5085,10006.0,14023.0,14922.0,14437.659
10,Florencia,73,75,75.0,76.000000,84.0,75.0,58,20,46.0,39.0,37.0,36.0,890,224,374.0,507.0,489.0,459.700
11,Ibagué,1010,973,964.0,919.000000,906.0,905.0,840,248,601.0,626.0,612.0,628.0,18612,2601,9108.0,11248.0,11669.0,11626.824
12,Montería,259,259,259.0,252.333333,239.0,241.0,200,60,102.0,137.0,137.0,122.0,3732,834,1021.0,933.0,1002.0,1237.730
13,Neiva,660,654,647.0,645.000000,633.0,632.0,441,152,250.0,264.0,271.0,267.0,6208,865,2393.0,3401.0,3290.0,3430.686
14,Pasto,502,502,502.0,502.000000,486.0,488.0,478,196,338.0,378.0,402.0,393.0,7992,977,3084.0,5204.0,5422.0,5808.573
15,Popayán,634,626,616.0,498.000000,466.0,466.0,467,116,265.0,296.0,321.0,313.0,6933,1594,3756.0,4077.0,4963.0,4598.268
16,Quibdó,194,194,174.0,160.333333,163.0,166.0,123,100,99.0,86.0,86.0,89.0,2778,1073,2088.0,1492.0,1414.0,1428.312
17,Santa Marta,679,673,666.0,658.000000,633.0,608.0,649,201,451.0,576.0,581.0,570.0,25948,7123,15723.0,21218.0,20230.0,20775.493
18,Sincelejo**,85,85,NaN,NaN,NaN,NaN,75,75,NaN,NaN,NaN,NaN,822,492,NaN,NaN,NaN,NaN
19,Tunja,532,532,532.0,532.000000,532.0,532.0,426,129,284.0,359.0,343.0,345.0,4330,446,1629.0,2371.0,2630.0,3269.446
20,Valledupar,484,482,482.0,482.000000,284.0,284.0,130,31,58.0,56.0,117.0,94.0,1573,47,187.0,276.0,1140.0,927.704
21,Villavicencio,1002,1002,1002.0,1002.000000,997.0,991.0,915,200,737.0,779.0,786.0,750.0,13395,1633,6817.0,8385.0,8129.0,7715.951

In [4]:
#TRATAMIENTO DE DATOS FALTANTES (ciudad de Sincelejo)
#PROPUESTA 1
#para eliminar filas con NaN, analizando los datos se encontró que la ciudad de Sincelejo posee poco datos para su tratamiento y éstos se
#encuentran alejados de las demás ciudades, por lo anterior tomamos la decisión de eliminarlos y no llenarlos con algún estadísticos de tendencia
# esto sería una opción viable, al ejecutar se elimina el registro de la ciudad de Sincelejo
df = df.dropna(how='any') # solo se ejecuta si se desea esta opción
df

,Áreas Metropolitanas y Ciudades,Promedio mensual de vehículos afiliados 2019,2020,2021,2022,2023,2024,Promedio mensual de vehículos en servicio 2019,2020,2021,2022,2023,2024,Total pasajeros transportados (miles) 2019,2020,2021,2022,2023,2024
0,Área Metropolitana de Barranquilla1,3397,3422,3412.0,3346.333333,3364.0,3283.0,3086,1686,2638.0,2624.0,2655.0,2534.0,68281,23213,38962.0,51919.0,49653.0,44527.547
1,Área Metropolitana de Bogotá2,15272,14665,14419.0,12912.666667,13330.0,12858.0,13907,11202,12294.0,11538.0,11869.0,11673.0,451580,117013,207075.0,360461.0,368084.0,395139.042
2,Área Metropolitana de Bucaramanga3,1304,1261,1243.0,1216.666667,1211.0,1185.0,1242,772,1002.0,977.0,925.0,930.0,19741,4114,7122.0,12728.0,13053.0,15082.321
3,Área Metropolitana de Cali4,1982,1992,1958.0,1964.333333,1797.0,1801.0,1397,885,645.0,1037.0,1008.0,1133.0,46794,11023,9814.0,26092.0,25553.0,28862.331
4,Área Metropolitana de Cúcuta5,1767,1739,1673.0,1653.000000,1671.0,1648.0,1432,733,1012.0,1085.0,1080.0,1104.0,18900,6790,12497.0,16092.0,16759.0,16312.188
5,Área Metropolitana de Manizales6,1030,1037,992.0,1005.000000,1015.0,1016.0,899,444,831.0,829.0,847.0,854.0,15805,2683,7734.0,11793.0,12193.0,12645.157
6,Área Metropolitana del Valle de Aburrá (Medell...,5819,5918,5925.0,5937.333333,5923.0,5899.0,5276,4047,4923.0,5074.0,5167.0,5183.0,175397,51178,102748.0,159206.0,164274.0,162934.413
7,Área Metropolitana Centro de Occidente (Pereira)8,833,839,826.0,910.000000,902.0,907.0,683,325,529.0,623.0,636.0,649.0,18234,4895,9620.0,15721.0,15457.0,16146.857
8,Armenia,341,344,343.0,344.000000,345.0,344.0,284,170,244.0,245.0,250.0,249.0,5322,1276,3185.0,4079.0,3848.0,4171.550
9,Cartagena,1151,1036,1012.0,869.333333,853.0,849.0,984,428,580.0,607.0,555.0,543.0,25602,5085,10006.0,14023.0,14922.0,14437.659
10,Florencia,73,75,75.0,76.000000,84.0,75.0,58,20,46.0,39.0,37.0,36.0,890,224,374.0,507.0,489.0,459.700
11,Ibagué,1010,973,964.0,919.000000,906.0,905.0,840,248,601.0,626.0,612.0,628.0,18612,2601,9108.0,11248.0,11669.0,11626.824
12,Montería,259,259,259.0,252.333333,239.0,241.0,200,60,102.0,137.0,137.0,122.0,3732,834,1021.0,933.0,1002.0,1237.730
13,Neiva,660,654,647.0,645.000000,633.0,632.0,441,152,250.0,264.0,271.0,267.0,6208,865,2393.0,3401.0,3290.0,3430.686
14,Pasto,502,502,502.0,502.000000,486.0,488.0,478,196,338.0,378.0,402.0,393.0,7992,977,3084.0,5204.0,5422.0,5808.573
15,Popayán,634,626,616.0,498.000000,466.0,466.0,467,116,265.0,296.0,321.0,313.0,6933,1594,3756.0,4077.0,4963.0,4598.268
16,Quibdó,194,194,174.0,160.333333,163.0,166.0,123,100,99.0,86.0,86.0,89.0,2778,1073,2088.0,1492.0,1414.0,1428.312
17,Santa Marta,679,673,666.0,658.000000,633.0,608.0,649,201,451.0,576.0,581.0,570.0,25948,7123,15723.0,21218.0,20230.0,20775.493
19,Tunja,532,532,532.0,532.000000,532.0,532.0,426,129,284.0,359.0,343.0,345.0,4330,446,1629.0,2371.0,2630.0,3269.446
20,Valledupar,484,482,482.0,482.000000,284.0,284.0,130,31,58.0,56.0,117.0,94.0,1573,47,187.0,276.0,1140.0,927.704
21,Villavicencio,1002,1002,1002.0,1002.000000,997.0,991.0,915,200,737.0,779.0,786.0,750.0,13395,1633,6817.0,8385.0,8129.0,7715.951

In [5]:
#PROPUESTA 2
#Buscando en la página www.dane.gov.co se encontró información histórica de dos períodos anteriores de la ciudad de Sincelejo en cuanto a las 3 variables
#de interés (promedio mensual vehículos afiliados, promedio mensual vehículos en servicio, total pasajeros transportados (miles))
#se decidió construir un archivo en excel con dichos valores
import pandas as pd
import numpy as np
#https://docs.google.com/spreadsheets/d/1yLgC57QVN818HZZfyvmVna00E2AYqMea/edit?usp=sharing&ouid=107046758298231097149&rtpof=true&sd=true
id_sincelejo = '1yLgC57QVN818HZZfyvmVna00E2AYqMea'
df_sincelejo = pd.read_excel(f'https://docs.google.com/uc?export=download&id={id_sincelejo}', header=0, usecols = "B:I,K:R,T:AA").loc[:1]
df_sincelejo

,Promedio mensual de vehículos afiliados,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Promedio mensual de vehículos en servicio,Unnamed: 11,...,Unnamed: 16,Unnamed: 17,Total pasajeros transportados (miles),Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26
0,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0,2023.0,2024.0,2017.0,2018.0,...,2023.0,2024.0,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0,2023.0,2024.0
1,85.0,85.0,85.0,85.0,NaN,NaN,NaN,NaN,76.0,75.0,...,NaN,NaN,1172.0,949.0,822.0,492.0,NaN,NaN,NaN,NaN

In [6]:
# Se tomaron las siguientes decisiones:
#1. en los datos faltantes de promedio mensual de vehículos afiliados y promedio mensual de vehículos en servicio usar medias móviles ya que no hay fluctuación de los valores

import pandas as pd
import numpy as np

# Identificar los NaN en la primera fila
nan_mask = df_sincelejo.iloc[1].isnull()

# Reemplazar los NaN en las columnas 5-8 por 85
df_sincelejo.iloc[1, 4:9][nan_mask[4:9]] = 85

# Reemplazar los NaN en las columnas 14-17 por 75
df_sincelejo.iloc[1, 12:17][nan_mask[12:17]] = 75


df_sincelejo

<ipython-input-6-632a025c95d6>:11: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_sincelejo.iloc[1, 4:9][nan_mask[4:9]] = 85
<ipython-input-6-632a025c95d6>:14: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_sincelejo.iloc[1, 12:17][nan_mask[12:17]] = 75

,Promedio mensual de vehículos afiliados,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Promedio mensual de vehículos en servicio,Unnamed: 11,...,Unnamed: 16,Unnamed: 17,Total pasajeros transportados (miles),Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26
0,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0,2023.0,2024.0,2017.0,2018.0,...,2023.0,2024.0,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0,2023.0,2024.0
1,85.0,85.0,85.0,85.0,85.0,85.0,85.0,85.0,76.0,75.0,...,75.0,75.0,1172.0,949.0,822.0,492.0,NaN,NaN,NaN,NaN

In [7]:
#2. en los datos faltantes de total pasajeros transportados en miles, se usará un modelo de regresión exponencial para pronosticar lo faltante
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit

# Datos
x_data = np.array([1, 2, 3, 4]) #representan los años 2017, 2018, 2010 y 2020
y_data = np.array([1172, 949, 822, 492])

# Función exponencial
def exponential(x, a, b):
    return a * np.exp(b * x)

# Ajustar la curva
popt, pcov = curve_fit(exponential, x_data, y_data)

# Predecir nuevos valores
x_predict = np.array([5, 6, 7, 8]) # representarían los años 2021, 2022, 2023 y 2024
y_predict = exponential(x_predict, *popt)

y_predict = y_predict.astype(int)
#y_predict
#los valores predichos son [449, 351, 275, 215]

In [8]:
#ahora ingresamos los pronósticos a la df_sincelejo
df_sincelejo.iloc[1, 20] =  449
df_sincelejo.iloc[1, 21] =  351
df_sincelejo.iloc[1, 22] =  275
df_sincelejo.iloc[1, 23] =  215
df_sincelejo

,Promedio mensual de vehículos afiliados,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Promedio mensual de vehículos en servicio,Unnamed: 11,...,Unnamed: 16,Unnamed: 17,Total pasajeros transportados (miles),Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26
0,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0,2023.0,2024.0,2017.0,2018.0,...,2023.0,2024.0,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0,2023.0,2024.0
1,85.0,85.0,85.0,85.0,85.0,85.0,85.0,85.0,76.0,75.0,...,75.0,75.0,1172.0,949.0,822.0,492.0,449.0,351.0,275.0,215.0

In [9]:
#recuperamos los períodos de estudio (2019, 2020, 2021, 2022, 2023, 2024) en la df_sincelejo
df_sincelejocompatible = df_sincelejo.iloc[:, [2,3,4,5,6,7,10,11,12,13,14,15,18,19,20,21,22,23]]
df_sincelejocompatible

,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26
0,2019.0,2020.0,2021.0,2022.0,2023.0,2024.0,2019.0,2020.0,2021.0,2022.0,2023.0,2024.0,2019.0,2020.0,2021.0,2022.0,2023.0,2024.0
1,85.0,85.0,85.0,85.0,85.0,85.0,75.0,75.0,75.0,75.0,75.0,75.0,822.0,492.0,449.0,351.0,275.0,215.0

In [10]:
#agregamos una columna a la izquierda con el nombre de la ciudad
df_sincelejocompatible.insert(0, 'Áreas Metropolitanas y Ciudades', 'Sincelejo')
df_sincelejocompatible

,Áreas Metropolitanas y Ciudades,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26
0,Sincelejo,2019.0,2020.0,2021.0,2022.0,2023.0,2024.0,2019.0,2020.0,2021.0,2022.0,2023.0,2024.0,2019.0,2020.0,2021.0,2022.0,2023.0,2024.0
1,Sincelejo,85.0,85.0,85.0,85.0,85.0,85.0,75.0,75.0,75.0,75.0,75.0,75.0,822.0,492.0,449.0,351.0,275.0,215.0

In [11]:
#organizamos el nombre de las columnas
columns_names2 = ['Áreas Metropolitanas y Ciudades', 'Promedio mensual de vehículos afiliados 2019', '2020','2021','2022 ','2023','2024', 'Promedio mensual de vehículos en servicio 2019', '2020','2021','2022','2023','2024', 'Total pasajeros transportados (miles) 2019', '2020','2021','2022','2023','2024 ']
df_sincelejocompatible.columns = columns_names2
df_sincelejocompatible

,Áreas Metropolitanas y Ciudades,Promedio mensual de vehículos afiliados 2019,2020,2021,2022,2023,2024,Promedio mensual de vehículos en servicio 2019,2020,2021,2022,2023,2024,Total pasajeros transportados (miles) 2019,2020,2021,2022,2023,2024
0,Sincelejo,2019.0,2020.0,2021.0,2022.0,2023.0,2024.0,2019.0,2020.0,2021.0,2022.0,2023.0,2024.0,2019.0,2020.0,2021.0,2022.0,2023.0,2024.0
1,Sincelejo,85.0,85.0,85.0,85.0,85.0,85.0,75.0,75.0,75.0,75.0,75.0,75.0,822.0,492.0,449.0,351.0,275.0,215.0

In [12]:
#Reemplazamos el registro de sincelejo luego de haber hecho los pronósticos
df.iloc[18] = df_sincelejocompatible.iloc[1]
df

,Áreas Metropolitanas y Ciudades,Promedio mensual de vehículos afiliados 2019,2020,2021,2022,2023,2024,Promedio mensual de vehículos en servicio 2019,2020,2021,2022,2023,2024,Total pasajeros transportados (miles) 2019,2020,2021,2022,2023,2024
0,Área Metropolitana de Barranquilla1,3397,3422,3412.0,3346.333333,3364.0,3283.0,3086,1686,2638.0,2624.0,2655.0,2534.0,68281,23213,38962.0,51919.0,49653.0,44527.547
1,Área Metropolitana de Bogotá2,15272,14665,14419.0,12912.666667,13330.0,12858.0,13907,11202,12294.0,11538.0,11869.0,11673.0,451580,117013,207075.0,360461.0,368084.0,395139.042
2,Área Metropolitana de Bucaramanga3,1304,1261,1243.0,1216.666667,1211.0,1185.0,1242,772,1002.0,977.0,925.0,930.0,19741,4114,7122.0,12728.0,13053.0,15082.321
3,Área Metropolitana de Cali4,1982,1992,1958.0,1964.333333,1797.0,1801.0,1397,885,645.0,1037.0,1008.0,1133.0,46794,11023,9814.0,26092.0,25553.0,28862.331
4,Área Metropolitana de Cúcuta5,1767,1739,1673.0,1653.000000,1671.0,1648.0,1432,733,1012.0,1085.0,1080.0,1104.0,18900,6790,12497.0,16092.0,16759.0,16312.188
5,Área Metropolitana de Manizales6,1030,1037,992.0,1005.000000,1015.0,1016.0,899,444,831.0,829.0,847.0,854.0,15805,2683,7734.0,11793.0,12193.0,12645.157
6,Área Metropolitana del Valle de Aburrá (Medell...,5819,5918,5925.0,5937.333333,5923.0,5899.0,5276,4047,4923.0,5074.0,5167.0,5183.0,175397,51178,102748.0,159206.0,164274.0,162934.413
7,Área Metropolitana Centro de Occidente (Pereira)8,833,839,826.0,910.000000,902.0,907.0,683,325,529.0,623.0,636.0,649.0,18234,4895,9620.0,15721.0,15457.0,16146.857
8,Armenia,341,344,343.0,344.000000,345.0,344.0,284,170,244.0,245.0,250.0,249.0,5322,1276,3185.0,4079.0,3848.0,4171.550
9,Cartagena,1151,1036,1012.0,869.333333,853.0,849.0,984,428,580.0,607.0,555.0,543.0,25602,5085,10006.0,14023.0,14922.0,14437.659
10,Florencia,73,75,75.0,76.000000,84.0,75.0,58,20,46.0,39.0,37.0,36.0,890,224,374.0,507.0,489.0,459.700
11,Ibagué,1010,973,964.0,919.000000,906.0,905.0,840,248,601.0,626.0,612.0,628.0,18612,2601,9108.0,11248.0,11669.0,11626.824
12,Montería,259,259,259.0,252.333333,239.0,241.0,200,60,102.0,137.0,137.0,122.0,3732,834,1021.0,933.0,1002.0,1237.730
13,Neiva,660,654,647.0,645.000000,633.0,632.0,441,152,250.0,264.0,271.0,267.0,6208,865,2393.0,3401.0,3290.0,3430.686
14,Pasto,502,502,502.0,502.000000,486.0,488.0,478,196,338.0,378.0,402.0,393.0,7992,977,3084.0,5204.0,5422.0,5808.573
15,Popayán,634,626,616.0,498.000000,466.0,466.0,467,116,265.0,296.0,321.0,313.0,6933,1594,3756.0,4077.0,4963.0,4598.268
16,Quibdó,194,194,174.0,160.333333,163.0,166.0,123,100,99.0,86.0,86.0,89.0,2778,1073,2088.0,1492.0,1414.0,1428.312
17,Santa Marta,679,673,666.0,658.000000,633.0,608.0,649,201,451.0,576.0,581.0,570.0,25948,7123,15723.0,21218.0,20230.0,20775.493
19,Sincelejo,85,85,85.0,85.000000,85.0,85.0,75,75,75.0,75.0,75.0,75.0,822,492,449.0,351.0,275.0,215.000
20,Valledupar,484,482,482.0,482.000000,284.0,284.0,130,31,58.0,56.0,117.0,94.0,1573,47,187.0,276.0,1140.0,927.704
21,Villavicencio,1002,1002,1002.0,1002.000000,997.0,991.0,915,200,737.0,779.0,786.0,750.0,13395,1633,6817.0,8385.0,8129.0,7715.951

In [13]:
#DATOS DUPLICADOS
duplicados1 = df.duplicated()
duplicados1
#no se encuentran registros duplicados

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
19    False
20    False
21    False
dtype: bool

In [14]:
##BASE DE DATOS #2, OPERACION DE PASAJEROS

import pandas as pd

# ID del archivo de Google Drive
id = '1BDBecnlRYz0mQ_0LZAb3DVoBnNqYjgcd'

# Intentar leer el archivo especificando el delimitador como ';'
url = f'https://docs.google.com/uc?export=download&id={id}'
oper = pd.read_csv(url, delimiter=';')

# Mostrar las primeras filas para verificar la carga correcta
oper.head()
oper.tail()

<ipython-input-14-8f74c283ed6b>:10: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  oper = pd.read_csv(url, delimiter=';')

,TERMINAL,CLASE_VEHICULO,NIVEL_SERVICIO,MUNICIPIO_ORIGEN_RUTA,MUNICIPIO_DESTINO_RUTA,FECHA_DESPACHO,HORA_DESPACHO,TIPO_DESPACHO,DESPACHOS,PASAJEROS
1048570,T.T. DE CARTAGENA,BUS,LUJO,13001,8001,01/30/2024 12:00:00 AM,17,ORIGEN,3,59
1048571,T.T. DE MEDELLÍN NORTE,BUS,LUJO,5001,20001,12/16/2022 12:00:00 AM,18,ORIGEN,1,41
1048572,T.T. DE MANIZALES,MICROBUS,LUJO,17001,17174,01/15/2024 12:00:00 AM,11,ORIGEN,6,113
1048573,T.T. DE FLORENCIA,MICROBUS,LUJO,18001,76001,03/26/2023 12:00:00 AM,12,ORIGEN,1,10
1048574,T.T. DE ARMENIA,MICROBUS,BASICO,63001,63190,01/21/2024 12:00:00 AM,22,ORIGEN,2,8

**Identificación y Tratamiento de Outliers**


*Conversión a numérico:*


Se utiliza *pd.to_numeric()* en la columna *PASAJEROS* con el parámetro *errors='coerce'*, lo que convierte cualquier valor no numérico en NaN.

Eliminación de filas con NaN:
Después de la conversión, se eliminan las filas con valores NaN en la columna *PASAJEROS* usando *dropna(subset=['PASAJEROS'])*. Esto asegura que solo queden valores numéricos en esa columna.

Cálculo del IQR:
Después de limpiar los datos, se calcula el rango intercuartílico (IQR) para identificar los valores extremos (outliers).

Filtrado y eliminación de outliers:
Se eliminan los valores fuera del rango permitido por el IQR, generando un DataFrame limpio de outliers.

In [15]:
import pandas as pd

# Cargar la base de datos (usando 'oper' como el DataFrame de operación de pasajeros)
id = '1BDBecnlRYz0mQ_0LZAb3DVoBnNqYjgcd'
url = f'https://docs.google.com/uc?export=download&id={id}'
oper = pd.read_csv(url, delimiter=';')

# Convertir la columna PASAJEROS a numérica (forzar conversión, eliminando o llenando con NaN los valores no numéricos)
oper['PASAJEROS'] = pd.to_numeric(oper['PASAJEROS'], errors='coerce')

# Eliminar las filas donde PASAJEROS sea NaN, ya que no son válidas para el análisis
oper = oper.dropna(subset=['PASAJEROS'])

# Paso 1: Calcular los cuartiles y el rango intercuartílico (IQR) para la columna PASAJEROS
Q1 = oper['PASAJEROS'].quantile(0.25)  # Primer cuartil (25%)
Q3 = oper['PASAJEROS'].quantile(0.75)  # Tercer cuartil (75%)
IQR = Q3 - Q1  # Rango intercuartílico

# Paso 2: Definir los límites para identificar los outliers
limite_inferior = Q1 - 1.5 * IQR
limite_superior = Q3 + 1.5 * IQR

# Paso 3: Filtrar los outliers (valores fuera del rango)
outliers = oper[(oper['PASAJEROS'] < limite_inferior) | (oper['PASAJEROS'] > limite_superior)]
print(f"Outliers detectados:\n{outliers}")

# Paso 4: Eliminar los outliers del DataFrame original
oper_sin_outliers = oper[(oper['PASAJEROS'] >= limite_inferior) & (oper['PASAJEROS'] <= limite_superior)]

# Verificar el número de filas antes y después de eliminar los outliers
print(f"Número de filas antes de eliminar outliers: {len(oper)}")
print(f"Número de filas después de eliminar outliers: {len(oper_sin_outliers)}")
oper_sin_outliers

<ipython-input-15-c62f087883e2>:6: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  oper = pd.read_csv(url, delimiter=';')

Outliers detectados:
                       TERMINAL CLASE_VEHICULO NIVEL_SERVICIO  \
12              T.T. DE AGUAZUL            BUS         BASICO
17           T.T. DE BOGOTÁ SUR       MICROBUS           LUJO
33       T.T. DE MEDELLÍN NORTE       MICROBUS         BASICO
75           T.T. DE FUSAGASUGA       MICROBUS           LUJO
77               T.T. DE IBAGUÉ            BUS           LUJO
...                         ...            ...            ...
1048533     T.T. DE SANTA MARTA            BUS           LUJO
1048547       T.T. DE MANIZALES            BUS           LUJO
1048554            T.T. DE CALI       MICROBUS         BASICO
1048570       T.T. DE CARTAGENA            BUS           LUJO
1048572       T.T. DE MANIZALES       MICROBUS           LUJO

         MUNICIPIO_ORIGEN_RUTA  MUNICIPIO_DESTINO_RUTA  \
12                       11001                   17524
17                       11001                   25307
33                        5001                    5697
75                       25290                   11001
77                       73001                   76001
...                        ...                     ...
1048533                   8001                   44430
1048547                  76001                   20001
1048554                  76001                   76111
1048570                  13001                    8001
1048572                  17001                   17174

                 FECHA_DESPACHO  HORA_DESPACHO TIPO_DESPACHO  DESPACHOS  \
12               1/08/2024 0:00              0      TRANSITO          1
17       01/27/2024 12:00:00 AM              6      TRANSITO          6
33               1/10/2024 0:00             17        ORIGEN          4
75               1/02/2024 0:00             13        ORIGEN         10
77               1/01/2024 0:00              8        ORIGEN          1
...                         ...            ...           ...        ...
1048533  01/13/2024 12:00:00 AM             10      TRANSITO          7
1048547  12/22/2022 12:00:00 AM             23      TRANSITO          2
1048554  10/13/2022 12:00:00 AM             11        ORIGEN          6
1048570  01/30/2024 12:00:00 AM             17        ORIGEN          3
1048572  01/15/2024 12:00:00 AM             11        ORIGEN          6

         PASAJEROS
12            42.0
17            68.0
33            76.0
75           188.0
77            44.0
...            ...
1048533       43.0
1048547       65.0
1048554       54.0
1048570       59.0
1048572      113.0

[88470 rows x 10 columns]
Número de filas antes de eliminar outliers: 1048543
Número de filas después de eliminar outliers: 960073

,TERMINAL,CLASE_VEHICULO,NIVEL_SERVICIO,MUNICIPIO_ORIGEN_RUTA,MUNICIPIO_DESTINO_RUTA,FECHA_DESPACHO,HORA_DESPACHO,TIPO_DESPACHO,DESPACHOS,PASAJEROS
0,T.T. DE BOGOTÁ SALITRE,BUS,LUJO,11001,15759,05/21/2023 12:00:00 AM,0,ORIGEN,1,27.0
1,T.T. DE AGUACHICA,BUS,LUJO,20011,54001,1/06/2024 0:00,23,ORIGEN,1,30.0
2,T.T. DE VILLAVICENCIO,MICROBUS,LUJO,50001,50590,01/15/2024 12:00:00 AM,7,ORIGEN,1,6.0
3,T.T. DE MELGAR,BUSETA,BASICO,11001,73001,1/11/2023 0:00,20,TRANSITO,2,0.0
4,T.T. DE MELGAR,MICROBUS,BASICO,11001,25001,1/11/2023 0:00,16,TRANSITO,1,0.0
...,...,...,...,...,...,...,...,...,...,...
1048568,T.T. DE BOGOTÁ SALITRE,MICROBUS,LUJO,11001,54498,1/08/2024 0:00,5,ORIGEN,1,4.0
1048569,T.T. DE MEDELLÍN NORTE,MICROBUS,BASICO,5001,5664,8/07/2021 0:00,5,ORIGEN,2,2.0
1048571,T.T. DE MEDELLÍN NORTE,BUS,LUJO,5001,20001,12/16/2022 12:00:00 AM,18,ORIGEN,1,41.0
1048573,T.T. DE FLORENCIA,MICROBUS,LUJO,18001,76001,03/26/2023 12:00:00 AM,12,ORIGEN,1,10.0
1048574,T.T. DE ARMENIA,MICROBUS,BASICO,63001,63190,01/21/2024 12:00:00 AM,22,ORIGEN,2,8.0

In [16]:
##se requiere agredar un cero a la izquierda  a las columnas MUNICIPIO_ORIGEN_RUTA y MUNICIPIO_DESTINO_RUTA para que todos los códigos queden con 5 dígitos
oper['MUNICIPIO_ORIGEN_RUTA'] = oper['MUNICIPIO_ORIGEN_RUTA'].astype(str).str.zfill(5)
oper['MUNICIPIO_DESTINO_RUTA'] = oper['MUNICIPIO_DESTINO_RUTA'].astype(str).str.zfill(5)
oper

# Guardar el archivo de vuelta a Excel si lo necesitas
#df.to_excel('tu_archivo_corregido.xlsx', index=False)

# Verificar la transformación
#print(df.head())

,TERMINAL,CLASE_VEHICULO,NIVEL_SERVICIO,MUNICIPIO_ORIGEN_RUTA,MUNICIPIO_DESTINO_RUTA,FECHA_DESPACHO,HORA_DESPACHO,TIPO_DESPACHO,DESPACHOS,PASAJEROS
0,T.T. DE BOGOTÁ SALITRE,BUS,LUJO,11001,15759,05/21/2023 12:00:00 AM,0,ORIGEN,1,27.0
1,T.T. DE AGUACHICA,BUS,LUJO,20011,54001,1/06/2024 0:00,23,ORIGEN,1,30.0
2,T.T. DE VILLAVICENCIO,MICROBUS,LUJO,50001,50590,01/15/2024 12:00:00 AM,7,ORIGEN,1,6.0
3,T.T. DE MELGAR,BUSETA,BASICO,11001,73001,1/11/2023 0:00,20,TRANSITO,2,0.0
4,T.T. DE MELGAR,MICROBUS,BASICO,11001,25001,1/11/2023 0:00,16,TRANSITO,1,0.0
...,...,...,...,...,...,...,...,...,...,...
1048570,T.T. DE CARTAGENA,BUS,LUJO,13001,08001,01/30/2024 12:00:00 AM,17,ORIGEN,3,59.0
1048571,T.T. DE MEDELLÍN NORTE,BUS,LUJO,05001,20001,12/16/2022 12:00:00 AM,18,ORIGEN,1,41.0
1048572,T.T. DE MANIZALES,MICROBUS,LUJO,17001,17174,01/15/2024 12:00:00 AM,11,ORIGEN,6,113.0
1048573,T.T. DE FLORENCIA,MICROBUS,LUJO,18001,76001,03/26/2023 12:00:00 AM,12,ORIGEN,1,10.0
1048574,T.T. DE ARMENIA,MICROBUS,BASICO,63001,63190,01/21/2024 12:00:00 AM,22,ORIGEN,2,8.0

In [ ]:
# Limpiar la columna FECHA_DESPACHO y la HORA_DESPACHO oganizar el formato de hora
# Convertir las fechas al formato deseado YYYY-MM-DD y Convertir a datetime para eliminar la parte de la hora
oper['FECHA_DESPACHO'] = pd.to_datetime(oper['FECHA_DESPACHO'], errors='coerce').dt.date
oper['HORA_DESPACHO'] = oper['HORA_DESPACHO'].apply(lambda x: f'{int(x):02}:00')
oper

<ipython-input-44-0bf53e4a30b9>:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  oper['FECHA_DESPACHO'] = pd.to_datetime(oper['FECHA_DESPACHO'], errors='coerce').dt.date

,TERMINAL,CLASE_VEHICULO,NIVEL_SERVICIO,MUNICIPIO_ORIGEN_RUTA,MUNICIPIO_DESTINO_RUTA,FECHA_DESPACHO,HORA_DESPACHO,TIPO_DESPACHO,DESPACHOS,PASAJEROS
0,T.T. DE BOGOTÁ SALITRE,BUS,LUJO,11001,15759,2023-05-21,00:00,ORIGEN,1,27.0
1,T.T. DE AGUACHICA,BUS,LUJO,20011,54001,2024-01-06,23:00,ORIGEN,1,30.0
2,T.T. DE VILLAVICENCIO,MICROBUS,LUJO,50001,50590,2024-01-15,07:00,ORIGEN,1,6.0
3,T.T. DE MELGAR,BUSETA,BASICO,11001,73001,2023-01-11,20:00,TRANSITO,2,0.0
4,T.T. DE MELGAR,MICROBUS,BASICO,11001,25001,2023-01-11,16:00,TRANSITO,1,0.0
...,...,...,...,...,...,...,...,...,...,...
1048570,T.T. DE CARTAGENA,BUS,LUJO,13001,08001,2024-01-30,17:00,ORIGEN,3,59.0
1048571,T.T. DE MEDELLÍN NORTE,BUS,LUJO,05001,20001,2022-12-16,18:00,ORIGEN,1,41.0
1048572,T.T. DE MANIZALES,MICROBUS,LUJO,17001,17174,2024-01-15,11:00,ORIGEN,6,113.0
1048573,T.T. DE FLORENCIA,MICROBUS,LUJO,18001,76001,2023-03-26,12:00,ORIGEN,1,10.0
1048574,T.T. DE ARMENIA,MICROBUS,BASICO,63001,63190,2024-01-21,22:00,ORIGEN,2,8.0

In [17]:
#Se llama la base de datos de la división política de Colombia con códigos de municipios del DANE
!gdown 1CMEqYcmeGh0zf9rXywAFegZ1xA9IVZAb # DIVIPOLITICA_Municipios.xlsx

Downloading...
From: https://drive.google.com/uc?id=1CMEqYcmeGh0zf9rXywAFegZ1xA9IVZAb
To: /content/DIVIPOLA_Municipios.xlsx
100% 128k/128k [00:00<00:00, 87.9MB/s]

In [18]:
import pandas as pd
import plotly.express as px
import geopandas as gpd

## Se leen los archivos como Dataframe

In [19]:
#DIVIPOLÍTICA_MUNICIPIOS, sólo se dejan las columnas código y Nombre de municipio

div = pd.read_excel('DIVIPOLA_Municipios.xlsx',header=10,usecols="C:D").loc[:1121]  # header y loc permiten seleccionar entre la fila 10 y 1121

div.rename(columns={'Código .1': 'Código'}, inplace=True)
div.rename(columns={'Nombre.1': 'Nombre'}, inplace=True)
div['Nombre'] = div['Nombre'].str.title() #La columna de departamentos se capitaliza ya que esta en mayusculas
div['Nombre'] = div['Nombre'].str.title() #La columna de municipios se capitaliza ya que esta en mayusculas
div

       Código          Nombre
0      5001.0        Medellín
1      5002.0       Abejorral
2      5004.0        Abriaquí
3      5021.0      Alejandría
4      5030.0           Amagá
...       ...             ...
1117  97889.0        Yavaraté
1118  99001.0  Puerto Carreño
1119  99524.0    La Primavera
1120  99624.0   Santa Rosalía
1121  99773.0        Cumaribo

[1122 rows x 2 columns]

In [20]:
#Para agregar un cero a los códigos y que todos tengan 5 dígitos, ya que en la base datos original aparecían códigos con 4
div['Código'] = div['Código'].astype(int).astype(str).str.zfill(5)
div

     Código          Nombre
0     05001        Medellín
1     05002       Abejorral
2     05004        Abriaquí
3     05021      Alejandría
4     05030           Amagá
...     ...             ...
1117  97889        Yavaraté
1118  99001  Puerto Carreño
1119  99524    La Primavera
1120  99624   Santa Rosalía
1121  99773        Cumaribo

[1122 rows x 2 columns]

## Ahora unimos las bases de datos con la función merge para concatenar el ID de los municipios con el nombre se los mismos

In [21]:
import pandas as pd

# **Base de datos 2: Operación de pasajeros y despachos**
id = '1BDBecnlRYz0mQ_0LZAb3DVoBnNqYjgcd'
url = f'https://docs.google.com/uc?export=download&id={id}'
oper = pd.read_csv(url, delimiter=';')

# Asegurarse de que los códigos de municipio tengan 5 dígitos
oper['MUNICIPIO_ORIGEN_RUTA'] = oper['MUNICIPIO_ORIGEN_RUTA'].astype(str).str.zfill(5)
oper['MUNICIPIO_DESTINO_RUTA'] = oper['MUNICIPIO_DESTINO_RUTA'].astype(str).str.zfill(5)

# **Limpiar la columna FECHA_DESPACHO y organizar el formato de HORA_DESPACHO**
# Convertir las fechas al formato deseado YYYY-MM-DD y convertir a datetime para eliminar la parte de la hora
oper['FECHA_DESPACHO'] = pd.to_datetime(oper['FECHA_DESPACHO'], errors='coerce').dt.date

# Organizar el formato de hora
# Asegurarse de que HORA_DESPACHO esté en formato HH:MM
oper['HORA_DESPACHO'] = oper['HORA_DESPACHO'].apply(lambda x: f'{int(x):02}:00' if pd.notnull(x) else '00:00')

# **Base de datos de DIVIPOLÍTICA de municipios**
div = pd.read_excel('DIVIPOLA_Municipios.xlsx', header=10, usecols="C:D").loc[:1121]
div.rename(columns={'Código .1': 'Código', 'Nombre.1': 'Nombre'}, inplace=True)
div['Nombre'] = div['Nombre'].str.title()
div['Código'] = div['Código'].astype(int).astype(str).str.zfill(5)

# **Unir el nombre del municipio de origen con la base de operaciones**
oper = pd.merge(oper, div[['Código', 'Nombre']], left_on='MUNICIPIO_ORIGEN_RUTA', right_on='Código', how='left')
oper.rename(columns={'Nombre': 'nombre_origen'}, inplace=True)

# **Unir el nombre del municipio de destino con la base de operaciones**
oper = pd.merge(oper, div[['Código', 'Nombre']], left_on='MUNICIPIO_DESTINO_RUTA', right_on='Código', how='left')
oper.rename(columns={'Nombre': 'nombre_destino'}, inplace=True)

# **Eliminar columnas duplicadas**
oper.drop(columns=['Código_x', 'Código_y'], inplace=True)
oper

<ipython-input-21-f793b9872873>:6: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  oper = pd.read_csv(url, delimiter=';')
<ipython-input-21-f793b9872873>:14: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  oper['FECHA_DESPACHO'] = pd.to_datetime(oper['FECHA_DESPACHO'], errors='coerce').dt.date

,TERMINAL,CLASE_VEHICULO,NIVEL_SERVICIO,MUNICIPIO_ORIGEN_RUTA,MUNICIPIO_DESTINO_RUTA,FECHA_DESPACHO,HORA_DESPACHO,TIPO_DESPACHO,DESPACHOS,PASAJEROS,nombre_origen,nombre_destino
0,T.T. DE BOGOTÁ SALITRE,BUS,LUJO,11001,15759,2023-05-21,00:00,ORIGEN,1,27,"Bogotá, D.C.",Sogamoso
1,T.T. DE AGUACHICA,BUS,LUJO,20011,54001,2024-01-06,23:00,ORIGEN,1,30,Aguachica,San José De Cúcuta
2,T.T. DE VILLAVICENCIO,MICROBUS,LUJO,50001,50590,2024-01-15,07:00,ORIGEN,1,6,Villavicencio,Puerto Rico
3,T.T. DE MELGAR,BUSETA,BASICO,11001,73001,2023-01-11,20:00,TRANSITO,2,0,"Bogotá, D.C.",Ibagué
4,T.T. DE MELGAR,MICROBUS,BASICO,11001,25001,2023-01-11,16:00,TRANSITO,1,0,"Bogotá, D.C.",Agua De Dios
...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,T.T. DE CARTAGENA,BUS,LUJO,13001,08001,2024-01-30,17:00,ORIGEN,3,59,Cartagena De Indias,Barranquilla
1048571,T.T. DE MEDELLÍN NORTE,BUS,LUJO,05001,20001,2022-12-16,18:00,ORIGEN,1,41,Medellín,Valledupar
1048572,T.T. DE MANIZALES,MICROBUS,LUJO,17001,17174,2024-01-15,11:00,ORIGEN,6,113,Manizales,Chinchiná
1048573,T.T. DE FLORENCIA,MICROBUS,LUJO,18001,76001,2023-03-26,12:00,ORIGEN,1,10,Florencia,Santiago De Cali
1048574,T.T. DE ARMENIA,MICROBUS,BASICO,63001,63190,2024-01-21,22:00,ORIGEN,2,8,Armenia,Circasia

DESCARGA DEL DATAFRAME EN EXCEL

In [22]:
# **Guardar el archivo resultante en formato Excel**
oper.to_excel('operacion_pasajeros_con_municipios.xlsx', index=False)

# Si estás en Google Colab o Jupyter y deseas descargar el archivo:
from google.colab import files
files.download('operacion_pasajeros_con_municipios.xlsx')